gazette/core

- topic/proto_framing.go
- topic/proto_framing_test.go
When using fixedFraming.Unpack from a hadoop-streaming application,
terminating newlines can persist in read key-value pairs. This change
makes the Unpack method tolerate these without throwing an error.
> Added tolerating terminating newline in Unpack.

- consumer/database.go
- consumer/database_test.go
- consumer/integration_test.go
- consumer/master.go
- consumer/pump_test.go
- consumer/replica.go
- consumer/routines.go
- consumer/routines_test.go
- consumer/runner.go
- consumer/shard_index.go
- consumer/shard_index_test.go
- consumer/test_support.go
- gazette/client.go
- journal/io.go
- journal/io_test.go
- journal/memory_broker.go
- journal/protocol.go
- recoverylog/fsm.go
- recoverylog/fsm_test.go
- recoverylog/integration_test.go
- recoverylog/playback.go
- recoverylog/playback_test.go
- recoverylog/recorded_op.proto
- recoverylog/recorder.go
- recoverylog/recorder_test.go
Formerly, `recoverylog` playback used behavior of waiting for a timeout
during which no new content became available from the broker. On
reaching that timeout, playback was assumed to be complete and the
consumer would switch from replicating to recording new state changes.
This invited race conditions, where a prior recorder which was delayed
in flushing final writes to the log would race with the new recorder.
Ordinarily FSMHints are sufficient to resolve the forked log history,
but this is a problem for other warm-standby replicas which are
live-tailing the log: depending on which raced write wins, they may
follow a fork of log history which is shutting down, and ignored the new
recorder entirely.
Fix this by changing player behavior to allow for injecting "hand-off"
noop RecordedOps, …
> recoverylog: make playback hand-off fast & deterministic

- gazette/read_api.go
- gazette/replicate_api.go
- gazette/router.go
- gazette/router_test.go
- gazette/tracing.go
- gazette/write_api.go
- gazetted/main.go
- journal/broker.go
- journal/broker_test.go
- journal/protocol.go
- journal/tail.go
- journal/tail_test.go
Each of the read, append, and replication APIs and operations are wired
with contexts and instrumentation for an associated optional trace.
PUB-4116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/8)
> instrument APIs with context and tracing

- cloudstore/sftp_fs.go
As written, this function will fail on newer versions of pkg/sftp, because they are now normalizing the errors from SSH errors to OS ones. This change accounts for that and restores isDir to working order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/12)
> Add check for os.ErrNotExist in isDir func

- .circleci/config.yml
- build/Dockerfile.gazette-base
- build/Dockerfile.gazette-build
- build/README.rst
- build/cmd/Dockerfile.gazette
- build/examples/Dockerfile.word-count
Use CircleCI 2.0 to test and build the Docker images. This PR is almost
complete, but still references Docker Hub images on "rupertchen" that
must be changed to "liveramp" once they are in place.
Jira: PUB-4350
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/17)
> Configure CircleCI 2.0

- README.rst
Adding the status badge serves two purposes:
1. It makes the status of the tests more visible.
2. It connects the source repository to the CI page.
Jira: PUB-4350
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/19)
> Add CircleCI status badge

- Gopkg.lock
- Gopkg.toml
- cloudstore/sftp_endpoint.go
- cloudstore/sftp_fs.go
- envflagfactory/factory.go
Previously, the socks server endpoint is discovered from the environment
variables SOCKS_SERVER_SERVICE_HOST and SOCKS_SERVER_SERVICE_PORT.
This change keeps this behavior but also allows the endpoint to be
configured via cli flag.
This change is for making it standard to discover Kubernetes Services using DNS rather than environment variables because we use ExternalName Services for cross-Namespace service discovery and ExternalName Services don't have environment variable support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/18)
> Make socks server endpoint a flag.

- envflag/envflag.go
- envflag/envflag_test.go
- envflag/example_test.go
- envflagfactory/factory.go
Prefer Kubernetes Service dns over env vars for service discovery
because env vars aren't available across Namespaces or for ExternalName
Services, and env vars are required at Pod startup, whereas dns is more
resilient to Endpoint updates.
Remove 127.0.0.1 as the default for discovering etcd and gazette
and expect Kubernetes first. Finally, remove _SERVICE_HOST and
_SERVICE_PORT since this will clobber the dns service discovery in favor
of the env vars, which we don't prefer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/23)
> Use Kubernetes Service dns for service discovery.

- Gopkg.lock
- cmd/gazctl/cmd/append.go
- cmd/gazctl/cmd/create.go
- cmd/gazctl/cmd/head.go
- cmd/gazctl/cmd/read.go
- cmd/gazctl/cmd/root.go
- cmd/gazctl/cmd/shard_compose.go
- cmd/gazctl/cmd/shard_compose_test.go
- cmd/gazctl/cmd/shard_metadata.go
- cmd/gazctl/cmd/shard_recover.go
- cmd/gazctl/cmd/shard_routes.go
- cmd/gazctl/main.go
- cmd/run-consumer/main.go
- pkg/consumer/interfaces.go
- pkg/consumer/routines.go
- pkg/consumer/routines_test.go
gazctl is an experimental CLI interface for interacting with Gazette.
It uses spf13's Cobra for help messages, command discovery, and
documentation. Viper is similarly used for configuration management.
Current commands support:
* Creating, reading from, and writing to journals.
* Recovering shard DBs to local disk from hints.
* Printing metadata about a recovered shard, including consumer
offsets.
* Composing new shard DBs from files & other database, updating
consumer offsets, and optionally recording into a recovery-log.
* Quering a consumer supporting the GRPC API and printing current
routes.
Tested:
* Unit coverage for shard-compose iterators.
* Manual testing of commands against local cluster / `stream-sum` example.
---
This change is [<img …
> gazctl: CLI tool for working with journals, consumers & shards

- cmd/gazctl/cmd/append.go
- cmd/gazctl/cmd/root.go
- cmd/gazctl/cmd/shard_prune_log.go
- cmd/gazctl/cmd/shard_recover.go
- pkg/consumer/integration_test.go
- pkg/consumer/master.go
- pkg/journal/fragment.go
- pkg/journal/fragment_test.go
- pkg/journal/index_watcher.go
- pkg/recoverylog/fsm.go
- pkg/recoverylog/fsm_test.go
- pkg/recoverylog/recorded_op.pb.go
- pkg/recoverylog/recorded_op.proto
- pkg/recoverylog/segment.go
- pkg/recoverylog/segment_test.go
This PR adds a `gazctl shard prune-log` command, as well as a number of related underlying changes.
Log pruning identifies Fragments of a hinted recovery log which can safely be removed, while preserving the ability to play back the pruned hints.
The intention is that regular pruning would be operational-ized by pointing `gazctl` as `.lastRecovered` hints of consumer shards.
Extensive testing against the `stream-sum` example was performed by:
* Heavily and continuously loading a local stack
* Regularly deleting the `stream-sum-summer` consumer pods, to force playback and recovery.
* Regularly using the `gazctl shard prune-log` command to prune both `.lastRecovered` and also primary hint paths.
* Verifying that no playback errors occurred.
---
This change is [<img …
> Identify and prune obsolete log fragments

- pkg/journal/io.go
- pkg/journal/io_test.go
- pkg/recoverylog/playback.go
AdjustedSeek performs a Seek taking into account a current buffer, which
may be able to satisfy the seek without involving the underlying reader.
In particular, this change prevents very short seeks from triggering a
re-open of the underlying reader.
Issue #51
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/52)
> Add RetryReader.AdjustedSeek, and use in recoverylog playback

- pkg/consumer/client.go
- pkg/consumer/client_test.go
Even if they're not explicitly listed in ConsumerState.Endpoints. This
allows clients to talk to PRIMARY shards hosted by members in the
process of shutting down. That shut-down could take a while, as shards
are recovered by other processes, and clients should be able to access
shards in the meantime.
Issue #50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/53)
> consumer: maintain GRPC connections to all PRIMARY endpoints

- pkg/cloudstore/filesystem.go
- pkg/cloudstore/sftp_fs.go
Currently if a copy is successful, but an error occurs while closing the
file, that error is discarded. We should have visibility on errors which
occur during the close.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/54)
> Add error check to Close in SFTP CopyAtomic

- pkg/gazette/write_service.go
- pkg/metrics/metrics.go
The log statement can be very spammy, and we don't look at it, so
instead, we should measure write failure rates and alert on those via
automation instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/55)
> Track failed writes as a metric rather than a log statement.

- pkg/cloudstore/sftp_fs.go
Within the Close function on SFTP Files, the condition is written such that if a file's write buffer is nil, the condition exits without flushing said buffer or closing the file. While the former is appropriate behavior, the latter is not. A File which has not had its Write function called (and therefore had a write buffer created) will never have its underlying file closed.
In particular, this presents an issue when used with the newer version of pkg/sftp we recently upgraded to. 
- The new version of the pkg/sftp File includes a ReadFrom function.
- The stdlib io.Copy function checks for the presence of a ReadFrom function on destination files. If present, it will prefer that over base Read/Write.
- CopyAtomic in the cloudstore package is implemented using io.Copy.
- When an SFTP file …
> Separate file close from buffer flush

- cmd/run-consumer/main.go
- pkg/consumer/replica.go
- pkg/consumer/routines.go
- pkg/metrics/metrics.go
We notice a lot of transient errors which create a lot of noise. Instead we'd like to push these failures to prometheus which can then be alerted on if we see a large number of them in a short period of time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/61)
> Track failures as metrics rather than log statements.

- pkg/cloudstore/s3_file.go
- pkg/cloudstore/s3_fs.go
As written, calls to CopyAtomic will read the entire source file to memory before sending it to the multipart upload function. Ideally, what we want is for the file to be uploaded in chunks so that the size of the spool doesn't get out of control. Restoring the old version of the CopyAtomic function will do exactly this (since under the hood io.Copy will call the Write function of s3File, which does this chunking).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/70)
> Fix behavior of CopyAtomic for S3 files

- Gopkg.lock
- cmd/gazconsumer/main.go
- pkg/metrics/metrics.go
We've run into problems where some of our consumer shards stay in the `Recovering` or `NotReading` state (as indicated by `gazconsumer`) for a long time, without being detected. This can occur for a number of reasons—underlying data loss in the journals, corrupted hints, running out of disk space, etc—which we have to manually solve before the shards can go back to the `OK` state. As such, we want to enable better monitoring of when consumer shards enter a different state and how long they stay there, so that we can configure our alerts accordingly and respond more promptly.
This initial approach registers one Prometheus gauge-type metric for each possible consumer shard state, where a 1 indicates that the shard is in that state and 0 if it is not. 
Other approaches we considered and …
> Log gazconsumer shard statuses 

- v2/pkg/broker/append_api.go
- v2/pkg/broker/append_api_test.go
- v2/pkg/broker/doc.go
- v2/pkg/broker/e2e_test.go
- v2/pkg/broker/integration/integration_test.go
- v2/pkg/broker/key_space.go
- v2/pkg/broker/list_apply_api.go
- v2/pkg/broker/list_apply_api_test.go
- v2/pkg/broker/pipeline.go
- v2/pkg/broker/pipeline_test.go
- v2/pkg/broker/read_api.go
- v2/pkg/broker/read_api_test.go
- v2/pkg/broker/replica.go
- v2/pkg/broker/replica_test.go
- v2/pkg/broker/replicate_api.go
- v2/pkg/broker/replicate_api_test.go
- v2/pkg/broker/resolver.go
- v2/pkg/broker/resolver_test.go
- v2/pkg/broker/service.go
- v2/pkg/broker/test_support_test.go
- v2/pkg/broker/teststub/broker.go
Package broker implements the broker runtime and protocol.BrokerServer
Read, Append, and Replicate APIs. Its `pipeline` type manages the
coordination of write transactions, and `resolver` the mapping of
journal names to Routes of responsible brokers. `replica` is a top-level
collection of runtime state and maintenance tasks associated with the processing
of a journal. gRPC proxy support is also implemented by this package.
Issue #72
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/90)
> broker: runtime and gRPC JournalServer

- v2/build/Dockerfile
Gazette only needs the RocksDB shared library, but the "install" make
target also builds and installs the static libraries [1]. Switching to
"install-shared" reduces the layer build time and the final size of the
image.
[1]: https://github.com/facebook/rocksdb/blob/5089e121166c46956a8a21c8ef967f1896c239de/Makefile#L1550
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/108)
> Skip building the RocksDB static library

- v2/build/all.sh
The image liveramp/gazette-base:2.1.0 is an up-to-date build of the
"base" stage. Most importantly, it allows subsequent builds to skip
building RocksDB.
For unknown reasons, to get builds of later stages to use cached layers
on CircleCI, a "--cache-from" option for each referenced earlier stage
is required. This is not required on local runs, but still works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/111)
> Leverage cached image layers in CircleCI

- v2/build/Dockerfile
- v2/build/all.sh
The vendor image replaces the "base" image as an image cache during CI
builds. It contains everything that was in the "base" target and
additionally adds the vendored source consistent with the latest
Gopkg.lock on the master branch.
Use of "docker --cache-from" is removed from non-CI builds (e.g., local
developer builds) as docker's local build cache persists between
executions and better handles cached image invalidation.
Connects #117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/118)
> Introduce "vendor" image as cache

- v2/pkg/broker/teststub/broker.go
- v2/pkg/client/appender.go
- v2/pkg/client/appender_test.go
- v2/pkg/client/list.go
- v2/pkg/client/list_test.go
- v2/pkg/client/reader.go
- v2/pkg/client/reader_test.go
- v2/pkg/client/retry_reader.go
- v2/pkg/recoverylog/recorder_rocksdb_test.go
Map gRPC errors having status that match local context errors, into the
well-known context error values. This simplifies error checks of client
responses.
Fixes #116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/120)
> client: consistent unwrapping of gRPC context errors

- v2/pkg/fragment/index.go
- v2/pkg/fragment/store_fs.go
- v2/pkg/fragment/store_gcs.go
- v2/pkg/fragment/store_s3.go
- v2/pkg/fragment/stores.go
When migrating from multiple Gazette clusters to a single one, it may be
desirable to not move existing fragments. However, this both forces the
name of the journal in the target cluster and may result in a name
conflict between two journals with the same name but different fragment
stores.
The "find"/"replace" query parameters implemented on "file", "s3", and
"gs" backends provides a workaround that avoids moving fragments.
For example, if previously there was
- `foo-topic/part-000` backed by `s3://bar-journals/`
- `foo-topic/part-000` backed by `gs://bar-journals/`
the two would collide in the target cluster despite being distinct
journals (unless one was renamed).
The example below shows how to give the journals different names in the
target cluster while still being backed by the …
> Support fragment store URL rewriting

- v2/pkg/fragment/store_fs.go
- v2/pkg/fragment/store_gcs.go
- v2/pkg/fragment/store_s3.go
- v2/pkg/fragment/stores.go
the backing store endpoint could be derived from the fragment object as needed so there is no need to pass in the endpoint to the `Remove` function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/150)
> clean up fragment store Remove function signature

- v2/cmd/gazctl/journals_reset_head.go
- v2/cmd/gazctl/main.go
- v2/pkg/allocator/flow_network_test.go
- v2/pkg/allocator/scenarios_test.go
- v2/pkg/broker/append_api.go
reset-head resets the append offset to the maximum offset of selected
journals. Also add a log statement in the broker for greater visibility.
Tested on a local stack by:
- running examples
- running reset-head (effective no-op).
- deleting all example journals, first preserving yaml
- re-applying yaml
- confirming that INDEX_HAS_GREATER_OFFSET errors were returned on attempted writes
- running reset-head
- confirming that write now proceed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/155)
> gazctl: add journals reset-head command

- v2/test/deploy_examples.sh
Minio did not use standard helm naming conventions in its helm chart, this has been fixed [here](https://github.com/helm/charts/commit/9874c2106664c79c763a08b30b2660fea4105eda) As a result of this change, the generated `journalspace` for the gazette examples will no longer resolve the fragment backends properly. This change updates the generated `journalspace` to properly reflect the new minio service name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/158)
> Update minio service name

- Gopkg.lock
- Gopkg.toml
- v2/build/Dockerfile
Ultimately we want to set the TTL for level compaction. This option was
immutable in v5.14.2 and made mutable in v5.15.x. Since we can only set
this option dynamically with the C bindings (after opening the DB), we
must upgrade our version of RocksDB.
Connects #112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/160)
> Update RocksDB from v5.14.2 to v5.17.2

- v2/cmd/gazctl/journals_apply.go
- v2/cmd/gazctl/journals_edit.go
- v2/cmd/gazctl/main.go
- v2/cmd/gazctl/shards_apply.go
- v2/cmd/gazctl/shards_edit.go
- v2/pkg/client/list.go
- v2/pkg/client/list_test.go
- v2/pkg/consumer/consumer_stub_test.go
- v2/pkg/consumer/shard_api.go
- v2/pkg/consumer/shard_api_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/161)
Connects #154
Connects #159
Please review commit by commit.
First commit:
There is an outstanding ticket (#154) to create a loopback server for testing against a consumer. This implements a basic loopback server in the model of the broker loopback server. This is a first pass implementation and sought to solve the problems introduced in writing tests for the second commit. As this testing tool is used more I expect it will be expanded upon. 
Second commit:
Add a max transaction size flag to all of the apply/edit commands in gazctl.
> Add max-txn-size flag to gazctl

- v2/cmd/gazctl/edit_docs.go
- v2/cmd/gazctl/journals_apply.go
- v2/cmd/gazctl/journals_edit.go
- v2/cmd/gazctl/journals_list.go
- v2/cmd/gazctl/journals_read.go
- v2/cmd/gazctl/journals_reset_head.go
- v2/cmd/gazctl/main.go
- v2/cmd/gazctl/shards_apply.go
- v2/cmd/gazctl/shards_edit.go
- v2/cmd/gazctl/shards_list.go
- v2/cmd/gazctl/shards_prune.go
With the number of commands growing and the volume of text in the
description of each, `main.go` was becoming difficult to read.
Implementing each command in a file (pre-existing) and adding it in an
`init` function (new change) places command documentation closer to its
implementation and is considered idiomatic by
github.com/jessevdk/go-flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/165)
> Decentralize adding of commands

- v2/examples/stream-sum/stream_sum.go
- v2/pkg/client/append_service.go
- v2/pkg/client/append_service_test.go
- v2/pkg/consumer/lifecycle.go
- v2/pkg/consumer/lifecycle_test.go
- v2/pkg/consumer/replica.go
- v2/pkg/consumer/shard_api.go
- v2/pkg/recoverylog/playback.go
- v2/pkg/recoverylog/playback_test.go
- v2/pkg/recoverylog/recorder.go
- v2/pkg/recoverylog/recorder_afero.go
- v2/pkg/recoverylog/recorder_rocksdb_test.go
- v2/pkg/recoverylog/recorder_test.go
Update all call-sites of AsyncAppend.Done with appropriate handling or
plumbing for AsyncAppend.Err.
consumer.NewReplica now creates an AppendService using the replica context,
and not context.Background, with the implication that all outstanding appends
are aborted immediately along with the replica.
Issue #163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/168)
> client: AppendService aborts AsyncAppends when context is cancelled.

- v2/pkg/allocator/flow_network.go
- v2/pkg/allocator/flow_network_test.go
- v2/pkg/allocator/scenarios_test.go
The allocator flow-network scales member capacities via calculated zone scaling
factors, which are designed to encourage appropriate balancing of items across
members.
But, we've seen edge cases with this scaling where a larger number of items does
not fully allocate across a smaller number of members, each having large
capacities. I suspect these cases are impossible to detect ahead of time,
without actually running push/relabel.
The core problem is we're artifically limiting the capacity of members in the
flow network. This PR undoes that limitation but preserves the incentive to
allocate items evenly across members, by introducing an "Overflow" node. Each
Member node having remaining capacity beyond it's scaled capacity, expresses
that excess via an arc to the Overflow. But, the …
> allocator: add "Overflow" node to network structure

- v2/cmd/gazctl/main.go
- v2/cmd/gazctl/shards_list.go
- v2/pkg/consumer/shard_api.go
gazctl shards list now takes `--lag` flag to see lag per source journal. Example:
```
+--------------------------+---------+-------------------------------------------------------+
|            ID            | STATUS  |                          LAG                          |
+--------------------------+---------+-------------------------------------------------------+
| c8d5b53b975c8d24b178bddb | PRIMARY | some/valid/journal/name/part-004:516583220768 |
+--------------------------+---------+-------------------------------------------------------+
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/176)
Connects #175
> gazctl shards list takes --lag flag

- v2/cmd/gazctl/main.go
- v2/test/deploy_examples.sh
Previously, `journals apply` and `shards apply` subcommands read from
stdin if the `--specs` option was not provided. This lead to the command
appearing hung if a user passed a file name but forgot to use `--specs`.
Stdin would be used and the filename, given as an arg, would be silently
ignored.
Taking a cue from `kubectl apply -f`, the `--specs` option is now
required. `--specs -` will read from stdin.
Connects #178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/182)
> Change how "gazctl {journals,shards} apply" takes stdin

- v2/pkg/fragment/store_fs.go
- v2/pkg/fragment/store_gcs.go
- v2/pkg/fragment/store_s3.go
- v2/pkg/fragment/stores.go
By introducing the `fragment.backend` interface and refactoring the
package-level functions, the many similar switch statements in
`stores.go` were removed. Furthermore, the metrics instrumentation in
each of the backend implementations were consolidated (moved "up") to
the operation and no longer require deferring a closure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/190)
> Replace conditionals with polymorphism

- v2/pkg/fragment/stores.go
"Ok" counters for store operations were erroneously being incremented on
both "Fail"s and "Ok"s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/192)
> Fix store operation metrics

- v2/pkg/fragment/store_gcs.go
With this change, gcsBackend#List ignores objects that represent
directories when iterating through the objects of a bucket for a
journal. Such objects never represent fragment files and attempting to
parse their names as such will almost certainly fail, writing a warning
to the logs when, in fact, everything is as expected.
Connects: #194
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/196)
> Remove extraneous warnings from GCS backed stores

- allocator/alloc_state.go
- allocator/alloc_state_test.go
- allocator/allocator.go
- allocator/benchmark_test.go
- allocator/flow_network.go
- allocator/item_state.go
- allocator/scenarios_test.go
- allocator/sparse_flow_network.go
- allocator/sparse_flow_network_test.go
- allocator/sparse_push_relabel/push_relabel.go
- allocator/sparse_push_relabel/push_relabel_test.go
- go.mod
- go.sum
- metrics/metrics.go
Hey gang,
This is a fundamental rework of the maximum-flow solver within the allocator. There were a few goals with this work, which I believe have been met:
* Achieve a more natural balancing of items across members and zones ("fair share" balancing), without relaxing desired solver constraints (at least 2 zones per item).
All constraints (2+ zones; member limits) and goals (uniform zone utilization & fair-share member balancing) are now directly captured within the flow-network architecture / max-flow solver. The "zone scaling factors" heuristic and zone sizing hacks are removed.
* Capable of scaling to 100K+ allocated items efficiently.
The `simulated-deploy` benchmark shows the new solver is about an order of magnitude faster on small graphs (eg N=5K is about 30ms vs 700ms-1s). For …
> allocator: sparse max-flow solver & flow network

- broker/fragment/doc.go
- broker/fragment/persister.go
- broker/fragment/store_fs.go
- broker/fragment/store_gcs.go
- broker/fragment/store_s3.go
- broker/fragment/stores.go
- broker/fragment/stores_test.go
- broker/protocol/fragment_extensions.go
- broker/protocol/fragment_extensions_test.go
- broker/protocol/fragment_store.go
- broker/protocol/rpc_extensions_test.go
ParseContentPath doesn't properly deal with name rewrites. Remove it
altogether, as it's fundamentally broken.
Also, expose S3StoreConfig, FileStoreConfig, and GSStoreConfig and
improve their respective godocs.
Issue #223
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/224)
> fragment: List uses ParseContentName instead of ParseContentPath

- cmd/gazctl/journals_prune.go
- docs/_static/cmd-gazctl-journals-prune.txt
Update the comment for the `gazctl journals prune` command to make it clearer why certain fragments with overlapping offsets are not deleted.
Context: https://gazette-dev.slack.com/archives/CK68U1XN0/p1576082261027100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/246)
> Clarify comment for "gazctl journals prune"

- broker/list_apply_api.go
- broker/list_apply_api_test.go
- broker/protocol/rpc_extensions.go
- broker/protocol/rpc_extensions_test.go
- cmd/gazctl/journals_apply.go
- cmd/gazctl/shards_apply.go
- consumer/protocol/rpc_extensions.go
- consumer/protocol/rpc_extensions_test.go
- consumer/shard_api.go
- consumer/shard_api_test.go
- docs/_static/cmd-gazctl-journals-apply.txt
- docs/_static/cmd-gazctl-journals-prune.txt
- docs/_static/cmd-gazctl-shards-apply.txt
This change addresses #244 which allows explicit ignoring of revision mismatches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/247)
> gazctl apply: interpret revision -1 as 'don't care'

- allocator/alloc_state.go
- allocator/alloc_state_test.go
- allocator/allocator_key_space.go
- allocator/allocator_key_space_test.go
- allocator/allocator_test.go
- allocator/announce_test.go
- allocator/benchmark_test.go
- allocator/flow_network_test.go
- allocator/item_state.go
- allocator/item_state_test.go
- allocator/scenarios_test.go
- allocator/sparse_flow_network_test.go
- broker/append_fsm.go
- broker/key_space.go
- broker/key_space_test.go
- broker/protocol/journal_spec_extensions.go
- broker/protocol/journal_spec_extensions_test.go
- broker/test_support_test.go
- brokertest/broker.go
- cmd/gazette/main.go
- consumer/key_space.go
- consumer/key_space_test.go
- consumer/protocol/shard_spec_extensions.go
- consumer/protocol/shard_spec_extensions_test.go
- consumer/test_support_test.go
- consumertest/consumer.go
- mainboilerplate/runconsumer/run_consumer.go
This allows `broker/protocol.JournalSpec.IsConsistent` to be hoisted out
of the `protocol` package and into the `broker` package instead, which
is a step towards removing all dependency on the `keyspace` package
(which in turn depends on `etcd`) from the `protocol` package.
A similar refactor is done for ShardIsConsistent which removes
dependence on `keyspace` & `etcd` from `consumer/protocol` as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/251)
> allocator: refactor ItemValue.IsConsistent into a free function callback

- broker/append_api.go
- broker/doc.go
- broker/fragment/doc.go
- broker/fragment/persister.go
- broker/fragment/spool.go
- broker/fragments_api.go
- broker/list_apply_api.go
- broker/read_api.go
- broker/replicate_api.go
- broker/service.go
- examples/stream-sum/stream_sum.go
- mainboilerplate/client.go
- mainboilerplate/diagnostics.go
- server/server.go
* More grpc-prometheus instrumentation
*  Remove broken response-time metric, add RPC starts & completions with operation & status.
* Add completed & persisted spools metric (allows for deriving persister queue depth).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/263)
> additional metrics work

- .gitignore
- docs/conf.py
- docs/overview-build-and-test.rst
Small docs update to help other new contributors get up to speed. The more commonly used build commands (using the `as-ci` target) are now closer to the top to emphasize their use over the plain make targets. Information about the plain build targets was moved toward the bottom, after a newly added section about required dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/268)
> Update build docs

- .github/workflows/ci-workflow.yaml
- Makefile
- mk/ci-builder.Dockerfile
- mk/common-build.mk
- mk/common-config.mk
This brings with it a few other changes to the build system:
- Building and publishing official release Docker images to docker hub
- Building and publishing binary releases to the Github Releases
- Build RocksDB with `PORTABLE=1` to prevent it from using
`-march=native`, which may cause it to use avx512 automatically
(meaning rocksdb would crash on hardware that doesn't support avx512).
This ensures that rocks will never use avx512.
- Changes how the 'ci-builder' docker image is built to allow taking
advantage of cache in GH actions instead of needing to publish the
image to docker hub
- Set the user id when invoking docker in the `as-ci` target so that the
output files won't be owned by the root user (fixes issues with
caching and allows removal without sudo)
- Added a new …
> Ci releases

- .github/workflows/ci-workflow.yaml
Turns out there were _two_ problems with the first attempt. One was that I had mistyped the registry name in the github secret (it should be `docker.io/gazette`). The second problem was that I had mistakenly used `as-ci` in the docker push step, which prevented docker from reading the correct credentials. Both of those have been addressed, so I'm hopeful that the master builds will succeed after this is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/270)
> don't use as-ci when pushing docker images

- .github/workflows/ci-workflow.yaml
Pull request builds were being run in the fork, and were not visible within the gazette repo. It seems that we need to trigger on `pull_request` in order to make those visible. The `push` trigger is now restricted only to the master branch so that we don't get multiple builds for the same PR.
Also, the version number used for the binaries was mssing the prefix, so I added that back in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/271)
> GH actions triggers and master version

- README.rst
- docs/overview-build-and-test.rst
- docs/overview-intro.rst
Just some minor docs updates related to the change from circleci to github actions. 
One thing that's _not_ covered here is the image names used in the kustomize templates. These currently use `gazette/broker` (without a registry host). One of the benefits(?) of docker hub is that it's the default registry, so image names without a host will automatically be pulled from there. There's a couple of ways that we could address that in the future, but one idea would be to add a `kustomization.yaml` that just modifies the image names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/272)
> migrate docs from circleci to github actions

- mk/common-build.mk
Some of the changes from #269 ended up breaking things for consumers that depend on the gazette make files. This addresses those issues, or at least the issues that showed up in the ping-pong example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/275)
> Fix downstream consumer builds

- broker/journalspace/node.go
- broker/journalspace/node_test.go
This is a follow up to the work done on #244 (in dd4539e546537da0faba64d95e9142dc77eaab89). Specifically, I missed:
> revision: -1 may be specified either at a directory or journal literal in JournalSpec YAML
Currently `revision: -1` _must_ be specified at the journal level, however, this change remedies this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/276)
> Allow explicit revision of -1 on directory nodes

- broker/journalspace/node.go
- broker/journalspace/node_test.go
- docs/brokers-journalspecs.rst
Updates broker/journalspace/node.go reverting the changes introduced in 5224810eacb90136d1a88259721b6df6be432f2c
and clarifies the documentation of revision:-1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/285)
> Etcd Revision clarifications

- broker/client/append_service.go
Previously, serveAppends failed to release buffers of appends which had
already been marked as error'd (due to, for example, a previously-read
context cancellation).
Ensure it does.
Issue #297
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/298)
> client: AppendService must release buffers of error'd AsyncAppends

- broker/client/append_service.go
- broker/client/append_service_test.go
Rather than using a global singleton Pool.
In the future this may allow for better coupling of resource quotas
and back-pressure against specific AppendService instances,
correlated to different consumer.Shards.
The immediate motivation is fixing a test-only bug, where a
mockFile{} fixture is added to the global Pool and causes a
future test case to fail.
Issue #297
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/299)
> client: AppendService owns its buffer sync.Pool

- broker/append_api_test.go
- brokertest/broker_test.go
GracefulStopTimeout can't be shrunk until after all connection setup has
occurred, as it's otherwise racing cmux matching of a mux for
newly-opened test connections.
See also soheilhy/cmux#76
Issue #301
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/302)
> brokertest: fix graceful stop test flake

- broker/client/reader.go
- broker/client/retry_reader.go
- broker/fragment/index.go
- broker/fragment/stores.go
- broker/protocol/dispatcher.go
- broker/protocol/endpoint.go
- broker/protocol/endpoint_test.go
- broker/protocol/journal_spec_extensions.go
- broker/protocol/journal_spec_extensions_test.go
- cmd/gazette/main.go
- consumer/protocol/shard_spec_extensions.go
- consumer/protocol/shard_spec_extensions_test.go
- consumer/recovery.go
- consumer/shard.go
- consumer/shard_api.go
- mainboilerplate/client.go
- mainboilerplate/runconsumer/run_consumer.go
- mainboilerplate/service.go
- server/server.go
Thematically this PR is a bag of quality-of-life improvements that make it easier to run local testing clusters.
* Make it possible to run vanilla shard / journal specs in a single-process cluster by bounding effective replication and disabling remote stores
* Support Unix domain sockets so as not to pollute the port space if you're running a lot of these test clusters
* Squelch a spurious warning.
See individual commits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/311)
> multiple improvements to facilitate local testing contexts

- consumer/resolver.go
- consumer/resolver_test.go
- consumer/shard.go
- consumer/test_support_test.go
If a shard assignment is removed (for example, because its FAILED)
and is then immediately re-created by the allocation coordinator,
we previously could fail to notice that the prior local shard was
invalidated and should be re-created.
Account for this by additionally monitoring the CreateRevision of
assignments and treating an assignment of the same or higher slot,
with a differing CreateRevision, as being a novel assignment which
requires a novel local shard to be boot-strapped.
Fixes #314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/315)
> consumer: shard transitions account for delete-then-create race

- broker/client/appender.go
- broker/client/doc.go
- broker/client/reader.go
- broker/client/retry_reader.go
- consumer/shard.go
Give particular focus to fragment reads, surfacing the number of
client-initiated fragment reads and related size metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/317)
> client: add new metric instrumentation for reads & appends

- message/publisher.go
- message/publisher_test.go
This is an experimental API to allow for publishing a message where the
content is not known until after the acknowledgement intents are needed.
This is a low level API to allow consumers a little more flexibility
when storing checkpoints in external systems, as Flow does for
materializations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/319)
> Add DeferPublishUncommitted to message.Publisher

- broker/fragment/store_s3.go
- broker/fragment/stores_test.go
Adds in support for `SSEKMSKeyId` by parsing it from the store url and passing it into the `S3StoreConfig`. Done analogously to the `SSE` paramater.
Also added a unit test for `parseStoreArgs` which checks that the `SSEKMSKeyId` field (amongst others) is correctly parsed from the store URL
Additional Testing:
- Ran `TestStoreInteractions` using `SSE` and `SSEKMSKeyId` parameters on a bucket with SSE KMS + key. Used this structure as the fragment store:  `s3://bucket-with-kms-key/?find=rwFind&replace=rwReplace&endpoint=https://region.amazonaws.com&sse=aws:kms&ssekmskeyid=test-key")` where  `test-key` matched the one on `bucket-with-kms-key`. The test ran successfully and was able to `Persist, List, Open/Read, and Delete` objects from the bucket. 
- With the above setup, I removed the …
> parse SSEKMSKeyId from store url and pass to store config

- cmd/gazctl/gazctlcmd/shards_unassign.go
- consumer/shard_api.go
This fixes a bug which caused the shard supervisor to stall indefinitely. If it ran `shards unassign` and there was nothing to be unassigned, it would never increment the etcd revision with its transaction. Then when we waited to observe our changes as reflected by the etcd mod revision, we would end up waiting until the next arbitrary transaction to complete. Needless to say, this is not the desired behavior.
Also adds a timeout to the command more generally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/322)
> `shards unassign` command no longer stalls

- server/server.go
Adds a function to server.go that allows passing the `net.Listener` used
with starting a Server. This is intended to allow users to create
servers using TLS.
Note that this is only a library change. No TLS options were added to Gazette binaries as of yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/327)
> Allow customizing server Listener

- consumer/shard_test.go
- consumer/transaction.go
This ensures txnRun fails-fast if StartCommit returns an error. If we don't do this, then txnStep will race a select over the shard's `readCh` with a select of the (failed) OpFuture, and then go on to call ConsumeMessage of a shard which is already in a failing state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/329)
> consumer: synchronously fail if StartCommit returns a pre-resolved error

- broker/fragment/store_s3.go
- consumer/store_sql_test.go
When the `region` configuration is missing the AWS S3 client will fail essentially all operations. This is true even if the `endpoint` is provided in the storage URL. Because the client is cached, this same failure will continue to happen, even _after_ you update `~/.aws/config` to set the `region`.
This commit adds an explicit check for the `Region` when initializing a new S3 client, to prevent the invalid client configuration from being persisted in the `clients` map.
This is not urgent or blocking, but I just wanted to get the fix in while I was thinking about it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/330)
> error when s3 client is missing region config

- keyspace/key_space.go
- keyspace/key_space_test.go
- kustomize/bases/etcd/etcd-bootstrap.sh
Fixes #337
It turns out that our assumptions about etcd watch responses weren't quite right. We had assumed that the `Header.Revision` would be the same as the highest `ModRevision` of the events within the response. While this happens to normally be the case, it is not guaranteed, and the revisions can differ significantly when the system is under heavy load. So we'd process a watch response that has a `Header.Revision` of `n`, but the most recent `ModRevision` of the contained `Events` was less than `n`. Then there's a subsequent watch response that _also_ has a `Header.Revision` of `n` that contains the remainder of the events up through revision `n`. But that second response gets ignored because the keyspace thinks it's already processed up through revision `n`.
This commit changes …
> Fix keyspace missing watch events

- keyspace/key_space.go
When processing watch events, update the persisted MemberId and RaftTerm. The `checkHeader` function logs any changes to these fields, as it's useful information for debugging. The last round of keyspace changes introduced a bug where we were no longer updating those fields if they changed after the initial keyspace load. This resulted in logging a warning on every subsequent watch event. This commit fixes that so that we once again only log on the first observation of the change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/338)
> keyspace: update MemberId/RaftTerm on watch events

- consumer/interfaces.go
- consumer/shard.go
Expose the status of the shard's primary processing loop to those who might care.
This allows applications to reliably detect when a shard has failed, and is a more reliable mechanism than the BeginFinisher interface because that interface is only called in the context of a current consumer transaction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/339)
> consumer: add Shard.PrimaryLoop() client.OpFuture

- broker/append_flow_control.go
- broker/append_flow_control_test.go
Allow up to ten seconds of unused flow-control credit to be banked against a future burst of traffic.
This is in service of workloads where clients want to write short burts of data and then go away for a while.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/340)
> broker: allow further banking of unused flow-control credit

- cmd/gazctl/gazctlcmd/shards_unassign.go
- consumer/shard_api.go
- consumer/shard_api_test.go
The API should remove assignments which are non-PRIMARY but are also FAILED.
Also update `gazctl` to process selected shards in batches, so that each RPC is of bounded size and under the Etcd transaction size limit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/343)
> shard unassign: handle non-PRIMARY assignments which are FAILED

- broker/fragment/store_azure.go
Azure URL signing was broken. The journal prefix was being duplicated in the URL, which resulted in unusable URLs. Clients would fail with a 403 response when attempting to fetch the fragment.  This removes the extra prefix to hopefully allow signing to work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/344)
> Fix azure pre-signed urls

- message/sequencer.go
- message/sequencer_test.go
If there are a large number of tracked message producers, Sequencer.HasPending() can become a hot loop since it's very frequently run. It's slow because it walks every journal producer to see if it has a larger offset than the last checkpoint offset.
Instead, maintain a set of *partialSeq which begin a new transactional sequence, and clear each *partialSeq upon dequeue of a sequence or rollback. Or, clear _all_ pending sequences upon a Checkpoint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/345)
> message: Sequencer incrementally tracks pending partial sequences

- cmd/gazctl/gazctlcmd/editor/editor.go
- cmd/gazctl/gazctlcmd/journals_edit.go
- cmd/gazctl/gazctlcmd/journals_list.go
- cmd/gazctl/gazctlcmd/journals_prune.go
- cmd/gazctl/gazctlcmd/shards_edit.go
- cmd/gazctl/gazctlcmd/shards_list.go
- cmd/gazctl/gazctlcmd/shards_prune.go
- cmd/gazctl/gazctlcmd/shards_unassign.go
This fixes an old bug in `shards prune` where it failed to use the `--broker.address` argument when creating the client.
In addition, this cleans up most of the places where gazctl subcommands were creating multiple new clients for a single operation, and consolidates down to a single client of each type per program invocation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/348)
> gazctl: re-use shard and journal clients

- cmd/gazctl/gazctlcmd/shards_prune.go
- cmd/gazctl/gazctlcmd/shards_recover.go
- consumer/recovery.go
- consumer/recoverylog/playback.go
If a shard is in a persistent state where it immediately becomes FAILED after recovery, it's very possible for the oldest recovered backup hints to actually be _newer_ than primary hints.
Then, if we prune without considering the primary hints, the shard is unable to recover from its log.
Fortunately this is easily remedied -- delete the primary hints while leaving backup recovery hints in place -- but better to not do it in the first place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/350)
> gazctl: shard pruning should consider all hints

- consumer/recoverylog/fsm.go
- consumer/recoverylog/fsm_test.go
In certain situations, if a RocksDB doesn't fully initialize then it may re-create its IDENTITY file upon the next next open attempt.
Currently this is prohibited by FSM but should be relaxed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/356)
> recoverylog: relax FSM to allow updating the content of a property

- broker/client/append_service.go
- broker/client/append_service_test.go
- broker/client/appender.go
- broker/client/appender_test.go
There are unavoidable scenarios where a client creates an intention to asynchronously write to a journal (as an AsyncAppend, or an checkpointed ACK intent), but the journal is deleted before the write can land.
Before, AppendService will loop forever awaiting the journal to come back into existence.
After, AppendService will discard writes to deleted or non-existant journals, logging a warning before doing so. This parallels the broker behavior of dropping spooled fragment data upon journal deletion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/357)
> broker/client: discard async appends of deleted journals

- broker/client/append_service.go
- broker/client/append_service_test.go
- broker/client/appender.go
- broker/client/appender_test.go
- consumer/transaction.go
- consumer/transaction_test.go
* Revert prior commit.
* Make ErrJournalNotFound a terminal error for AppendService, because it's essentially never recoverable and should be retried at a higher level.
* Have client.Appender handle insufficient journal brokers, as this _is_ a retry-able case that happens.
* Update consumer to relax the writes of recovered ACK intents. Log a missing journal but allow the session to proceed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/358)
> take two: relax ErrJournalNotFound only when writing recovered ACKs

- broker/client/append_service.go
- broker/client/append_service_test.go
Partially roll back a prior commit which began erroring on JOURNAL_NOT_FOUND. There are allowable data races where a created journal is assigned to a primary broker, whose Etcd watch is currently still unaware that the journal even exists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/359)
> AppendService should retry on JOURNAL_NOT_FOUND

- cmd/gazctl/gazctlcmd/shards_prune.go
- consumer/recoverylog/segment.go
- consumer/recoverylog/segment_test.go
Allows adding a "covering" segment to a `SegmentSet`. Given an non-empty set, this permits adding a segment that completely covers a subset of existing segments and has `LastOffset: 0`.  This is needed in order to reduce backup and primary hints into the same set, which is needed by `shards prune` in order to prune recovery logs conservatively.
I realized that the other fix is truly not necessary, because the existing behavior of zeroing the final segment of each set of hints is retained, and serves the same purpose.
With this change, I'm able to successfully dry-run pruning all the shards in Estuary's production environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/ …
> SegmentSet.Add allow missing LastOffset

- broker/fragment/store_s3.go
- broker/fragment/stores_test.go
Previously s3 stores could only use the region available via a given profile or the AWS application default credentials. This adds the ability to set an alternate region in the endpoint URL for an s3 fragment store for buckets that are in a different region.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/365)
> broker/fragment: region support for s3 stores

- consumer/shard.go
- consumer/shard_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/366)
> consumer: bound the size of an error stored as Etcd shard status

- broker/client/reader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/370)
> journal client: use http1.1 for fetching fragments, for real this time

- mainboilerplate/client.go
Rely only on stream-level flow control, and allow a single broker transport to multiplex LOTS of journals without a flow control deadlock, even if some are not being actively read.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/371)
> mainboilerplate: use a maximum-size connection flow control window

- consumer/store-sqlite/store.cpp
We had been manually hacking this into our headers to build locally for over a year. I _believe_ this is their correct final resting place, or at least this change allows Gazette to build on my Mac without hacks.
This fix appears to come from https://github.com/zeromq/zmqpp/issues/164.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/392)
> fix: Add missing endian conversion macros to enable MacOS builds

- broker/fragment/store_azure.go
Instead of crashing the whole broker when we fail to refresh an `azblob.TokenCredential`, we should retry forever and log noisily instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/391)
> azure: Don't panic when token refresh fails

- broker/client/reader.go
- broker/client/retry_reader.go
JOURNAL_NOT_FOUND is generally not a retry-able condition. It was orignally made so with a "shrug", on the premise that users may create journals after they had started their consumers. In practice, I'm not aware of any utility for it.
Also tweak logging to reduce noise in environments that have many journals with no current append volume, where read re-authorizations are somewhat frequently obtained.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/397)
> broker/client: surface JOURNAL_NOT_FOUND from RetryReader

- cmd/gazette/main.go
- mainboilerplate/runconsumer/run_consumer.go
- mainboilerplate/service.go
- server/server.go
For Gazette and consumers. Previously, the default (4MB) was used and could not be changed. Now it's configurable by flag and environment variable for brokers and consumers:
--broker.max-grpc-recv-size=  Maximum size of gRPC messages accepted by this server, in bytes (default: 4194304) [$BROKER_MAX_GRPC_RECV_SIZE]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/398)
> make the maximum accepted gRPC message size configurable

- broker/client/list.go
- broker/client/reader.go
- broker/client/retry_reader.go
Don't warn on a clean server-side close of a List RPC that doesn't ever return a response. This is expected for a resumed listing which doesn't change.
Use an attached Route of a previously completed Read, if available, and more importantly: clear the last Response of the previous stream. We could enter a condition where this was never cleared (for example, on NOT_JOURNAL_BROKER) if the _following_ request went to the correct broker, stayed open for a while with no data, and was then closed server-side. This can cause mis-leading and false-positive logged warnings.
Update RetryReader to account for attempt being incremented on the next loop iteration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> broker/client: quiet more noisy logging

- cmd/gazette/main.go
- mainboilerplate/runconsumer/run_consumer.go
Some existing clients are not as nimble at distinguishing the explicit empty vs implicit empty cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/401)
> grpc-gateway: emit default (zero-value) fields

- server/server.go
This was causing issues on Windows 11, which would give users pop-ups for them to select a client certificate to send to us.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/403)
> server: update TLS config to not request a client cert at all

- message/sequencer.go
Adds a bunch more information to a panic message emitted by the sequencer, in an effort to troubleshoot the cause of the panic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/404)
> Add more information to se1quencer panic message

- message/sequencer.go
- message/sequencer_test.go
Sequencer's runtime assertion checks were slightly too strong. A scenario we encountered which tripped a runtime panic was:
- CONTINUE_TXN messages were read from a journal, and were then part of a checkpoint. The checkpoint included the producer's earlier last ACK clock and a begin offset at the first of these messages.
- The messages were then duplicated within the journal, and ACKed.
- A new Sequencer recovers from the checkpoint.
- It reads the later, duplicated messages and adds them to the ring, followed by an ACK which begins a dequeue with a replay-read of the earlier messages.
- The earlier messages are dequeued first, and then the replay ends and hands off to the ring.
- Sequencer blows up because the first ring message is not strictly larger than the largest Clock dequeued from …
> message: account for duplicates across a recovered checkpoint boundary

- keyspace/key_space.go
We should continue to poll the watch channel after Unknown errors rather then bailing out with a terminal error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/407)
> keyspace: Etcd watch can retry on Unknown gRPC errors

- go.mod
- go.sum
This pulls in the fix for an issue that could cause the etcd client to use an incorrect revision when re-starting a watch after an etcd server failure. This presented as a crash in production due to receiving a watch event with a revision equal to (not greater) than the last processed revision. It was difficult to follow the discussion in the etcd issues, but this comment sums it up nicely:
https://github.com/etcd-io/etcd/pull/15248#issuecomment-1420125977
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/408)
> update etcd dependency

- broker/fragment/store_azure.go
We ran into this when a customer changed their storage account name. Fragment listings for their journal were returning errors complaining about resolving the hostname of the _previous_ storage account, even through the fragment spec correctly specified new storage account name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/409)
> azure: Invalidate storage client if storage account name changes

- broker/append_fsm.go
This can happen if we were primary, but have been re-assigned as a replica without an observed cancellation of our assignment in between.
We must tear down the stale pipeline to release replica spools before we return it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/414)
> broker: tear down a stale append pipeline before proxying

- allocator/allocator.go
- allocator/allocator_test.go
- allocator/item_state_test.go
- allocator/scenarios_test.go
- broker/append_fsm.go
- broker/resolver.go
- broker/resolver_test.go
Second attempt at making sure pipelines are released in this scenario.
Under this approach, we cancel the whole replica and build a new one, relying on the existing replica cancellation and shutdown behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/415)
> broker: tear down and restart a demoted replica

- allocator/allocator.go
- allocator/benchmark_test.go
- allocator/sparse_flow_network.go
- broker/append_fsm.go
- broker/fragment/index.go
- broker/fragment/index_test.go
- broker/replicate_api_test.go
ItemSlots may be unevenly distributed amoung assignment sub-problems.
We need to account for this, by scaling member ItemLimits by the relative portion of assignment slots that must be allocated within each sub-problem, rather than just the relative number of items.
Also, tune journal suspension to apply the journal's configured flush interval when evaluating whether the index is "dirty".
See individual commits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/416)
> scale allocator member ItemLimit to the relative share of ItemSlots, and refine suspension eligibility

- broker/resolver.go
- broker/resolver_test.go
- consumer/resolver.go
- consumer/resolver_test.go
Even if the header is present. This matches broker behavior, and allows clients to send along Etcd revisions to await (received from a peer), which can speed overall adjustments to topology changes within the cluster.
Also tweak errors to not assume that requests with headers imply proxied requests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/417)
> consumer: resolution should allow omitted ProcessId

- broker/replica.go
This is a safety valve if there are frequent topology changes in the cluster, since those changes will slow down auto-suspensions.
It also provides an opportunity for a primary which is newly-added to the topology to observe fragment uploads which may have arrived after its first fragment refresh interval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/420)
> broker: require the topology is stable for longer before auto-suspending

- message/sequencer.go
Otherwise, the ring will indefinetely retain messages which have already been processed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/422)
> message: nil out dequeued Envelope.Message after consumption

- auth/auth.go
- mainboilerplate/client.go
BROKER_AUTH_TOKEN and CONSUMER_AUTH_TOKEN, when present, are used as pre-shared bearer authorization tokens submitted with client requests.
This enables `gazctl` and other client applications to make use of pre-shared authorization tokens which are negotiated as part of a larger authorization context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/432)
> add client support for pre-shared authorization tokens

- broker/fragment/index.go
Currently we will immediately skip forward a read if it begins at offset zero.
However, we also see cases where a long-disabled task will come back online, observe an ACK, and then attempt a replay-read from an offset fixed in its recovery log. These reads block for the full offset jump threshold.
Resolve this by skipping forward any read having an offset behind the minimum available offset of journal content.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/437)
> fragment: slightly relax offset skip behavior

- broker/client/append_service.go
- broker/client/append_service_test.go
Added ErrJournalNotFound and ErrWrongAppendOffset to the list of non-retryable errors that break out of the append retry loop.
Updated tests to cover the new error types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/439)
> feat: handle additional non-retryable errors in append service

- broker/stores/health_check.go
- broker/stores/stores_test.go
GCS, and possibly other stores, have rate limits on how quickly an object may be updated that we sometimes see. It succeeds on retry, but the 5 minute interval when all is okay was motivated by testing, and is perhaps too aggressive in production.
Also increase jitter to quickly spread out the health checks of blocks of brokers starting at correlated times.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/440)
> stores: increase OK health-check interval and jitter
