gazette/core

- mainboilerplate/boilerplate.go
Jira: PUB-4415
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/5)
> Serve runtime profiling data via HTTP

- build/Dockerfile.gazette-build
- consensus/allocator.go
- consensus/tree_ops.go
- consumer/interfaces.go
- consumer/test_support.go
- gazette/client.go
- journal/interfaces.go
Jira: PUB-4451
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/7)
> Generate mocks via go:generate directives

- cloudstore/filesystem.go
@joshk0 could you take a look at this one please? Please lmk if I should tag someone else (although you seem to have contributed quite a lot to this file).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/11)
> INTL-549 Fetch S3 region dynamically

- Gopkg.lock
- pkg/consensus/allocator.go
- pkg/consensus/retry_watcher.go
- pkg/consensus/retry_watcher_test.go
- pkg/consensus/watcher_test.go
Addresses https://github.com/LiveRamp/gazette/issues/24.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/40)
> Use a periodic full refresh in RetryWatcher.

- pkg/recoverylog/playback.go
- pkg/recoverylog/playback_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/58)
> Lost segments

- Gopkg.lock
- Gopkg.toml
- build/Dockerfile.gazette-base
- build/Dockerfile.gazette-build
- build/cmd/Dockerfile.gazette
- build/examples/Dockerfile.stream-sum
- build/examples/Dockerfile.word-count
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/80)
> Upgrade rocksdb version to 14.2

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/103)
> Install bash

- .circleci/config.yml
Use CircleCI workflows in order to integrate with the GitHub Checks API. As an
added bonus, execute v1 and v2 jobs in parallel.
https://circleci.com/blog/see-the-status-of-your-circleci-workflows-in-github/
a7f0bf0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/107)
> Test CircleCI GH Checks

- v2/test/README.rst
The documentation was a little unclear as to where and how some of these commands should be run so I attempted to clear them up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/109)
> fix /v2/test/README.rst

- v2/cmd/gazctl/journals_read.go
- v2/cmd/gazctl/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/123)
Connects #48
> gazctl journal read implementation for reading from a set of journals to stdout

- v2/cmd/gazctl/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/125)
> update gazctl read help

- v2/build/lib.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/128)
> Fix build script for local runs

- v2/cmd/gazette/main.go
- v2/pkg/broker/append_api_test.go
- v2/pkg/broker/replica.go
- v2/pkg/brokertest/broker.go
- v2/pkg/fragment/persister.go
- v2/pkg/fragment/persister_test.go
- v2/pkg/fragment/spool.go
- v2/pkg/fragment/spool_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/127)
> Fetch latest JournalSpec and apply update the backing store before appending.

- v2/pkg/fragment/store_fs.go
- v2/pkg/fragment/store_gcs.go
- v2/pkg/fragment/store_s3.go
- v2/pkg/fragment/stores.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/133)
> add ability to remove fragments from v2 fragment stores

- Gopkg.lock
- v2/charts/consumer/templates/deployment.yaml
- v2/charts/consumer/values.yaml
- v2/examples/stream-sum/stream_sum_test.go
- v2/examples/word-count/word_count_test.go
- v2/pkg/broker/read_api_test.go
- v2/pkg/brokertest/broker.go
- v2/pkg/consumer/interfaces.go
- v2/pkg/consumer/lifecycle.go
- v2/pkg/consumer/lifecycle_test.go
- v2/pkg/consumer/replica.go
- v2/pkg/consumer/replica_test.go
- v2/pkg/consumer/resolver_test.go
- v2/pkg/consumer/shard_api.go
- v2/pkg/consumer/shard_api_test.go
- v2/pkg/consumer/store_json_file.go
- v2/pkg/consumer/test_support_test.go
- v2/pkg/consumertest/consumer.go
- v2/pkg/consumertest/consumer_test.go
- v2/pkg/etcdtest/etcd.go
- v2/pkg/message/fixed_framing.go
- v2/pkg/message/interfaces.go
- v2/pkg/message/json_framing.go
- v2/pkg/message/routines.go
- v2/pkg/message/routines_test.go
- v2/pkg/server/server.go
Please review commit-by-commit, each is independent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/135)
> Collection of smaller changes from application testing

- v2/pkg/protocol/protocol.pb.go
- v2/pkg/protocol/protocol.proto
As per the task, the comment was unclear as to when various components of the read response were being returned to the comments have been updated to be more explicit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/148)
Connects #122
> update ReadResponse WriteHead & Fragment  comment

- v2/charts/consumer/templates/deployment.yaml
- v2/charts/consumer/values.yaml
- v2/charts/gazette/templates/deployment.yaml
- v2/charts/gazette/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/166)
> deployment template now supports annotations

- v2/pkg/broker/append_api.go
- v2/pkg/fragment/spool.go
- v2/pkg/fragment/store_gcs.go
- v2/pkg/fragment/store_s3.go
- v2/pkg/fragment/stores.go
- v2/pkg/metrics/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/170)
> first pass gaz v2 broker metrics

- v2/pkg/fragment/stores.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/174)
> fix broker fragment store metrics

- v2/pkg/consumer/lifecycle.go
- v2/pkg/metrics/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/177)
> add bytes consumed metric

- v2/pkg/fragment/store_gcs.go
- v2/pkg/fragment/store_s3.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/183)
> stat correct error in store

- v2/pkg/fragment/store_s3.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/184)
> return correct value from s3Exists

- v2/pkg/keyspace/key_space.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/187)
Connects #186
> keyspace.Load passes expectSameRevision false to patchHeader

- v2/pkg/keyspace/key_space.go
The broker's initial load of the KeySpace after announcing itself to the
cluster was racing the allocator's attempt to schedule it.
KeySpace#Load uses a mirror.Syncer to receive a range of keys over a
channel of type clientv3.GetResponse. It was assumed that the response
revision would be identical to the revision in the request. This turns
out to be false; it represents the revision of the key-value store when
generating the [response][1]. Therefore, it's possible for the revisions
in a sync to increase over a single load attempt.
In fact, this is common in practice because a broker announces itself
prior to calling KeySpace#Load triggering the allocator to schedule it,
writing the new schedule to etcd.
cabc807 was the first attempt to address this, but was flawed because it
required …
> Relax etcd revision check on KeySpace#Load

- v2/pkg/keyspace/key_space_test.go
Connects #186
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/189)
> Update unit test

- v2/build/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/180)
> add vim to gazette docker image

- v2/pkg/consumer/lifecycle.go
- v2/pkg/consumer/lifecycle_test.go
- v2/pkg/recoverylog/playback.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/liveramp/gazette/203)
> two bug fixes

- v2/pkg/keyspace/key_space.go
- v2/pkg/keyspace/key_space_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/205)
> progress notify events no longer update keyspace revision

- .circleci/config.yml
- README.rst
- cmd/gazette/main.go
- mainboilerplate/config.go
- mainboilerplate/diagnostics.go
- mainboilerplate/runconsumer/run_consumer.go
- mk/build.mk
- mk/ci-builder.Dockerfile
- mk/config.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/207)
> circleci: update for Makefile build system

- docs/goals_and_nongoals.md
Fixes a couple of minor grammar errors in the "Goals and Nongoals" document.
> Minor corrections to goals_and_nongoals.md

- README.md
- broker/append_fsm.go
- broker/client/append_service.go
- docs/append_txns.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/228)
> docs: new design overview for append transactions

- cmd/gazctl/shards_prune.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/249)
> Do not attempt to prune a shard if it has no segments

- broker/key_space.go
- broker/list_apply_api.go
- broker/protocol/ext/doc.go
- broker/protocol/ext/header_extensions.go
- broker/protocol/ext/header_extensions_test.go
- broker/protocol/ext/route_extensions.go
- broker/protocol/ext/route_extensions_test.go
- broker/protocol/header_extensions.go
- broker/protocol/header_extensions_test.go
- broker/protocol/route_extensions.go
- broker/protocol/route_extensions_test.go
- broker/replica.go
- broker/resolver.go
- broker/resolver_test.go
- brokertest/broker.go
- consumer/resolver.go
- consumer/resolver_test.go
- consumer/shard_api.go
- consumertest/consumer.go
- go.mod
- go.sum
Removes etcd dependencies from broker/client and broker/protocol
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/250)
> remove etcd dependency from broker/client and broker/protocol

- docs/cncf_proposal.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/253)
> first draft of cncf proposal

- metrics/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/258)
> Adds WriteHead metric to GazetteBrokerCollectors

- broker/fragment/stores_test.go
- consumer/recovery_test.go
- consumer/transaction_test.go
- examples/stream-sum/stream_sum.go
- examples/stream-sum/stream_sum_test.go
- message/publisher.go
- message/sequencer.go
- metrics/metrics.go
The action is in the final commit. Included a few other commits fixing / instrumenting minor test flakes you can skip over if desired. Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/260)
> address UUID sequencing race

- broker/client/appender.go
- message/sequencer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/264)
> two more metrics-related fixes

- CHANGELOG.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/277)
> update changelog in preparation for 0.88.0 release

- consumer/interfaces.go
- consumer/resolver.go
- consumer/resolver_test.go
- consumer/shard.go
- mainboilerplate/runconsumer/run_consumer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/281)
> Shard up metric

- broker/fragment/store_azure.go
- broker/fragment/stores.go
- broker/protocol/fragment_store.go
- go.mod
- go.sum
Implements `fragment.backend` for azure using `github.com/Azure/azure-storage-blob-go`. Additional required configuration for `azureBackend` is setting two new environment variables `AZURE_ACCOUNT_NAME` and `AZURE_ACCOUNT_KEY` (similar to configuration of `GOOGLE_APPLICATION_CREDENTIALS` for `gcsBackend`)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/287)
> Azure store

- etcdtest/etcd.go
- etcdtest/etcd_default.go
- etcdtest/etcd_linux.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/321)
> work around for platform dependent test setup

- cmd/gazctl/gazctlcmd/shards_recover.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/325)
> gazctl: add shards recoverylog-play command

- broker/fragment/store_azure.go
- go.mod
- go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/342)
> chore: Bump `github.com/Azure/azure-storage-blob-go` to `v0.15.0`

- broker/fragment/store_azure.go
We must refresh whenever the credential expires _before_ 1 minute from now, not after.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/349)
> Azure AD: fix my dumb mistake when refreshing user delegation credentials

- broker/fragment/store_azure.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/395)
> small bug fix for mutex on store_azure

- message/sequencer.go
The output of the previous panic message was way too large, and was truncated. So this changes to separate logs of each of the things that we'd like to see.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/405)
> use separate log statements for sequencer diagnostics

- broker/fragment/store_azure.go
For a period of time until the next retry, which is now controlled by returning a short interval until the next refresh. It's perfectly fine if attempts to use the storage pipeline result in errors.
Crucially, don't spin forever attempting to refresh the credential, as this blocks the current goroutine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/431)
> store_azure: if token refresh fails, allow the credential to be invalid

- cmd/gazctl/gazctlcmd/gazctl.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gazette/core/446)
> gazctlcmd: register stores in gazctl
